language: node_js
node_js:
  - "node"
cache: npm
script:
  - bash deploy.sh
before_deploy:
  - cd dist
deploy:
  provider: pages
  local_dir: build
  skip-cleanup: true
  github-token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
