language: node_js
node_js:
  - "node"
deploy:
  provider: pages
  project: ./dist/
  skip-cleanup: true
  github-token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
