language: node_js
node_js:
  - "node"
cache: npm
script:
  - npm run build
after_success:
  - cd dist
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push "https://${GITHUB_PAT}@github.com/msquaredc/msquaredc.github.io" master > /dev/null 2>&1
